<?php
/**
 * Request handler (last modified: 2026.04.21).
 *
 * This file is a part of the "common classes package", utilised by a number of
 * packages and projects, including CIDRAM and phpMussel.
 * @link https://github.com/Maikuolan/Common
 *
 * License: GNU/GPLv2
 * @see LICENSE.txt
 *
 * "COMMON CLASSES PACKAGE" COPYRIGHT 2019 and beyond by Caleb Mazalevskis.
 * *This particular class*, COPYRIGHT 2021 and beyond by Caleb Mazalevskis.
 */

namespace Maikuolan\Common;

class Request extends CommonAbstract
{
    /**
     * @var int The default timeout to use when one isn't specified for a given request.
     */
    public $DefaultTimeout = 12;

    /**
     * @var array Alternative channels to use for requests matching specific patterns.
     */
    public $Channels = ['Triggers' => []];

    /**
     * @var string Disabled channels CSV.
     */
    public $Disabled = '';

    /**
     * @var bool Whether to send the results of outbound requests to stdout.
     */
    public $SendToOut = false;

    /**
     * @var string Object-level logger for the results of outbound requests.
     */
    public $ObjLogger = '';

    /**
     * @var string Whether to dump the object-level logger to a file (and where to find it).
     */
    public $ObjLoggerFile = '';

    /**
     * @var string The URL of a proxy to use if required by the instance.
     */
    public $Proxy = '';

    /**
     * @var string The username and password to use if required by the specified proxy URL.
     */
    #[Context(Sensitive: true)]
    public $ProxyAuth = '';

    /**
     * @var string The default user agent to cite (implementations *should* override
     *  this with a user agent of their own, in order to properly inform servers of
     *  the implementation's identity.
     */
    public $UserAgent = 'Request class (https://github.com/Maikuolan/Common)';

    /**
     * @var int The most recent status code generated by the instance.
     */
    public $MostRecentStatusCode = 0;

    /**
     * @var int What to try using for sending requests.
     *      0: Nothing is available; Can't process requests.
     *      1: Just use curl (curl is installed/available; default).
     *      2: Try using fopen with stream_context_create (curl isn't installed/available).
     */
    public $TryUsing = 1;

    /**
     * @var array PHP disabled functions (populated by the constructor).
     */
    private $DF = [];

    /**
     * @var int Default stream blocksize (128KB).
     */
    private const STREAM_BLOCKSIZE = 131072;

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        /** Disabled functions check. */
        $this->DF = \array_flip(\explode(',', \ini_get('disable_functions') ?: ''));

        if (
            \extension_loaded('curl') &&
            \function_exists('curl_init') &&
            !isset($this->DF['curl_init']) &&
            \function_exists('curl_setopt') &&
            !isset($this->DF['curl_setopt']) &&
            \function_exists('curl_exec') &&
            !isset($this->DF['curl_exec'])
        ) {
            return;
        }
        if (
            !\ini_get('open_basedir') &&
            \ini_get('allow_url_fopen') &&
            \function_exists('stream_context_create') &&
            !isset($this->DF['stream_context_create']) &&
            \function_exists('fopen') &&
            !isset($this->DF['fopen']) &&
            \function_exists('feof') &&
            !isset($this->DF['feof']) &&
            \function_exists('fread') &&
            !isset($this->DF['fread'])
        ) {
            $this->TryUsing = 2;
        }
        $this->TryUsing = 0;
    }

    /**
     * Allow calling the instance as a function (proxies to request).
     *
     * @return string
     */
    public function __invoke(...$Params): string
    {
        return $this->request(...$Params);
    }

    /**
     * Object destructor. Used to write the object-level logger to a file when necessary.
     *
     * @return void
     */
    public function __destruct()
    {
        /** Guard. */
        if ($this->ObjLogger === '' || $this->ObjLoggerFile === '') {
            return;
        }

        $WriteMode = \file_exists($this->ObjLoggerFile) ? 'ab' : 'wb';
        $Handle = \fopen($this->ObjLoggerFile, $WriteMode);
        if (!\is_resource($Handle)) {
            return;
        }
        \fwrite($Handle, $this->ObjLogger);
        \fclose($Handle);
    }

    /**
     * The main request method.
     *
     * @param string $URI The resource to request.
     * @param mixed $Params If empty or omitted, CURLOPT_POST is false. Otherwise,
     *      CURLOPT_POST is true, and the parameter is used to supply
     *      CURLOPT_POSTFIELDS. Normally an associative array of key-value pairs,
     *      but can be any kind of value supported by CURLOPT_POSTFIELDS. Optional.
     * @param int $Timeout An optional timeout limit.
     * @param array $Headers An optional array of headers to send with the request.
     * @param int $Depth Recursion depth of the current closure instance.
     * @param string $Method The request method to use (if not GET or POST).
     * @return string The results of the request, or an empty string upon failure.
     */
    public function request(string $URI, $Params = [], int $Timeout = -1, array $Headers = [], int $Depth = 0, string $Method = ''): string
    {
        /** Guard. */
        if (!$this->TryUsing) {
            return '';
        }

        /** Option overrides (currently used only for manually overriding CURLOPT_SSL_VERIFYPEER). **/
        $Overrides = [];

        /** Test channel triggers. */
        foreach ($this->Channels['Triggers'] as $TriggerName => $TriggerURI) {
            /** Ensures only the channel data for a channel matching the current URI is loaded for this specific method instance. */
            if (!isset($this->Channels[$TriggerName]) || !\is_array($this->Channels[$TriggerName]) || \substr($URI, 0, \strlen($TriggerURI)) !== $TriggerURI) {
                continue;
            }

            foreach ($this->Channels[$TriggerName] as $Channel => $Options) {
                if (!\is_array($Options) || !isset($Options[$TriggerName])) {
                    continue;
                }
                $Len = \strlen($Options[$TriggerName]);
                if (\substr($URI, 0, $Len) !== $Options[$TriggerName]) {
                    continue;
                }
                unset($Options[$TriggerName]);
                if (empty($Options) || $this->inCsv(\key($Options), $this->Disabled)) {
                    continue;
                }
                $AlternateURI = \current($Options) . \substr($URI, $Len);
                break;
            }
            if ($this->inCsv($TriggerName, $this->Disabled)) {
                if (isset($AlternateURI)) {
                    return $this($AlternateURI, $Params, $Timeout, $Headers, $Depth, $Method);
                }
                return '';
            }
            if (isset($this->Channels['Overrides'], $this->Channels['Overrides'][$TriggerName])) {
                $Overrides = $this->Channels['Overrides'][$TriggerName];
            }
            break;
        }

        $IsHTTPS = \strtolower(\substr($URI, 0, 6)) === 'https:';

        /** Using fopen with stream_context_create instead of curl. */
        if ($this->TryUsing === 2) {
            if (!empty($Params) && \gettype($Params) === 'array' && \function_exists('http_build_query') && !isset($this->DF['http_build_query'])) {
                $Post = true;
                $PostData = \http_build_query($Params);
                $Headers['Content-Type'] = 'application/x-www-form-urlencoded';
            } else {
                $Post = false;
                $PostData = '';
            }
            if ($Method !== '') {
                $MethodToUse = $Method;
            } else {
                $MethodToUse = $Post ? 'POST' : 'GET';
            }
            $Context = ['http' => ['method' => $MethodToUse, 'timeout' => $Timeout > 0 ? $Timeout : $this->DefaultTimeout, 'follow_location' => 1, 'max_redirects' => 1, 'ignore_errors' => true]];
            if (!isset($Headers['Accept-Language'])) {
                $Headers = ['Accept-Language' => 'en-AU,en-US;q=0.9,en;q=0.8'] + $Headers;
            }
            $Headers['User-Agent'] = $this->UserAgent;
            if ($this->Proxy !== '') {
                $Context['http']['proxy'] = $this->Proxy;
                $Context['http']['request_fulluri'] = true;
                if ($this->ProxyAuth !== '') {
                    $Headers['Proxy-Authorization'] = 'Basic ' . \base64_encode($this->ProxyAuth);
                }
            }
            $Build = [];
            foreach ($Headers as $HeaderName => $HeaderValue) {
                $Build[] = $HeaderName . ': ' . $HeaderValue;
            }
            $Context['http']['header'] = \implode("\r\n", $Build);
            unset($HeaderValue, $HeaderName, $Build);
            if ($PostData !== '') {
                $Context['http']['content'] = $PostData;
            }
            if ($IsHTTPS) {
                $Cert = '';
                if (\function_exists('openssl_get_cert_locations') && !isset($this->DF['openssl_get_cert_locations'])) {
                    $Certs = \openssl_get_cert_locations();
                    if (!empty($Certs['ini_cafile']) && \is_readable($Certs['ini_cafile'])) {
                        $Cert = $Certs['ini_cafile'];
                    } elseif (!empty($Certs['default_cert_file_env']) && \is_readable($Certs['default_cert_file_env'])) {
                        $Cert = $Certs['default_cert_file_env'];
                    }
                }
                if ($Cert !== '') {
                    $VPeer = isset($Overrides['CURLOPT_SSL_VERIFYPEER']) ? !empty($Overrides['CURLOPT_SSL_VERIFYPEER']) : false;
                    $Context['ssl'] = [
                        'verify_peer' => $VPeer,
                        'verify_peer_name' => $VPeer,
                        'allow_self_signed' => false,
                        'cafile' => $Cert
                    ];
                } else {
                    $Context['ssl'] = [
                        'verify_peer' => false,
                        'verify_peer_name' => false,
                        'allow_self_signed' => false,
                        'cafile' => false
                    ];
                }
            }
            $Context = \stream_context_create($Context);

            $Time = \microtime(true);
            $Handle = \fopen($URI, 'rb', false, $Context);
            if (!\is_resource($Handle)) {
                return '';
            }

            /** Content of the request response. */
            $Response = '';
            while (!\feof($Handle)) {
                $Response .= \fread($Handle, self::STREAM_BLOCKSIZE);
            }

            \fclose($Handle);
            $Time = \microtime(true) - $Time;

            if (\function_exists('http_get_last_response_headers')) {
                $RHeaders = \http_get_last_response_headers();
                if (isset($RHeaders[0]) && \substr($RHeaders[0], 0, 4) === 'HTTP' && ($SPos = \strpos($RHeaders[0], ' ')) !== false) {
                    $Code = (int)\substr($RHeaders[0], $SPos + 1, 3);
                }
            }
            if (isset($Code)) {
                $this->sendMessage(\sprintf('%s - %s - %s - %s', $MethodToUse, $URI, $Code, (\floor($Time * 100) / 100) . 's'));
                $this->MostRecentStatusCode = $Code;

                /** Request failed. Try again using an alternative address. */
                if ($Code >= 400 && isset($AlternateURI) && $Depth < 3) {
                    return $this($AlternateURI, $Params, $Timeout, $Headers, $Depth + 1, $Method);
                }
            } else {
                $this->sendMessage(\sprintf('%s - %s - %s - %s', $MethodToUse, $URI, 200, (\floor($Time * 100) / 100) . 's'));

                /** Assuming 200, because no reliable way to tell otherwise without http_get_last_response_headers (and $http_response_header is deprecated as of PHP8.5). */
                $this->MostRecentStatusCode = 200;
            }

            /** Return the results of the request. */
            return $Response;
        }

        /** Initialise the cURL session. */
        $Request = \curl_init($URI);

        \curl_setopt($Request, \CURLOPT_FRESH_CONNECT, true);
        \curl_setopt($Request, \CURLOPT_HEADER, false);
        if (empty($Params)) {
            \curl_setopt($Request, \CURLOPT_POST, false);
            $Post = false;
        } else {
            \curl_setopt($Request, \CURLOPT_POST, true);
            \curl_setopt($Request, \CURLOPT_POSTFIELDS, $Params);
            $Post = true;
        }
        if ($IsHTTPS) {
            \curl_setopt($Request, \CURLOPT_PROTOCOLS, \CURLPROTO_HTTPS);
            \curl_setopt($Request, \CURLOPT_SSL_VERIFYPEER, (
                isset($Overrides['CURLOPT_SSL_VERIFYPEER']) ? !empty($Overrides['CURLOPT_SSL_VERIFYPEER']) : false
            ));
            $Cert = '';
            if (\function_exists('openssl_get_cert_locations') && !isset($this->DF['openssl_get_cert_locations'])) {
                $Certs = \openssl_get_cert_locations();
                if (!empty($Certs['ini_cafile']) && \is_readable($Certs['ini_cafile'])) {
                    $Cert = $Certs['ini_cafile'];
                } elseif (!empty($Certs['default_cert_file_env']) && \is_readable($Certs['default_cert_file_env'])) {
                    $Cert = $Certs['default_cert_file_env'];
                }
            }
            if ($Cert !== '') {
                \curl_setopt($Request, \CURLOPT_CAINFO, $Cert);
            }
        }
        if ($Method !== '') {
            \curl_setopt($Request, \CURLOPT_CUSTOMREQUEST, $Method);
            $DebugMethod = $Method;
        } else {
            $DebugMethod = $Post ? 'POST' : 'GET';
        }
        if ($this->Proxy !== '') {
            \curl_setopt($Request, \CURLOPT_PROXY, $this->Proxy);
            if ($this->ProxyAuth !== '') {
                \curl_setopt($Request, \CURLOPT_PROXYUSERPWD, $this->ProxyAuth);
            }
        }
        \curl_setopt($Request, \CURLOPT_FOLLOWLOCATION, true);
        \curl_setopt($Request, \CURLOPT_MAXREDIRS, 1);
        \curl_setopt($Request, \CURLOPT_RETURNTRANSFER, true);
        \curl_setopt($Request, \CURLOPT_TIMEOUT, ($Timeout > 0 ? $Timeout : $this->DefaultTimeout));
        \curl_setopt($Request, \CURLOPT_USERAGENT, $this->UserAgent);
        \curl_setopt($Request, \CURLOPT_HTTPHEADER, $Headers ?: []);
        $Time = \microtime(true);

        /** Execute and get the response. */
        $Response = \curl_exec($Request);

        $Time = \microtime(true) - $Time;

        /** Check for problems (e.g., resource not found, server errors, etc). */
        if (($Info = \curl_getinfo($Request)) && \is_array($Info) && isset($Info['http_code'])) {
            $this->sendMessage(\sprintf('%s - %s - %s - %s', $DebugMethod, $URI, $Info['http_code'], (\floor($Time * 100) / 100) . 's'));
            $this->MostRecentStatusCode = $Info['http_code'];

            /** Request failed. Try again using an alternative address. */
            if ($Info['http_code'] >= 400 && isset($AlternateURI) && $Depth < 3) {
                if (\PHP_VERSION_ID < 80000) {
                    \curl_close($Request);
                }
                return $this($AlternateURI, $Params, $Timeout, $Headers, $Depth + 1, $Method);
            }
        } else {
            $this->sendMessage(\sprintf('%s - %s - %s - %s', $DebugMethod, $URI, 200, (\floor($Time * 100) / 100) . 's'));
            $this->MostRecentStatusCode = 200;
        }

        /** Close the cURL session (PHP < 8). */
        if (\PHP_VERSION_ID < 80000) {
            \curl_close($Request);
        }

        /** Return the results of the request. */
        return $Response;
    }

    /**
     * Checks for a value within CSV, or within a normal list if not CSV.
     *
     * @param string $Value The value to look for.
     * @param string $CSV The CSV to look in.
     * @return bool True when found; False when not found.
     */
    public function inCsv(string $Value, string $CSV): bool
    {
        if ($Value === '' || $CSV === '') {
            return false;
        }
        $Arr = \strpos($CSV, ',') === false && \strpos($CSV, "\n") !== false ? \explode("\n", $CSV) : \explode(',', $CSV);
        if (\strpos($CSV, '"') !== false) {
            foreach ($Arr as &$Item) {
                if (\substr($Item, 0, 1) === '"' && \substr($Item, -1) === '"') {
                    $Item = \substr($Item, 1, -1);
                }
            }
        }
        return \in_array($Value, $Arr, true);
    }

    /**
     * Sends messages to stdout.
     *
     * @param string $Message The message to send.
     * @return void
     */
    public function sendMessage(string $Message): void
    {
        $this->ObjLogger .= '[' . \date('Y-m-d\Th:i:sO', \time()) . '] ' . $Message . "\n";
        if ($this->SendToOut !== true) {
            return;
        }
        $Handle = \fopen('php://stdout', 'wb');
        \fwrite($Handle, "\r" . $Message . "\n");
        \fclose($Handle);
    }
}
