<?php
/**
 * Request handler (last modified: 2026.04.30).
 *
 * This file is a part of the "common classes package", utilised by a number of
 * packages and projects, including CIDRAM and phpMussel.
 * @link https://github.com/Maikuolan/Common
 *
 * License: GNU/GPLv2
 * @see LICENSE.txt
 *
 * "COMMON CLASSES PACKAGE" COPYRIGHT 2019 and beyond by Caleb Mazalevskis.
 * *This particular class*, COPYRIGHT 2021 and beyond by Caleb Mazalevskis.
 */

namespace Maikuolan\Common;

class Request extends CommonAbstract
{
    /**
     * @var int The default timeout to use when one isn't specified for a given request.
     */
    public $DefaultTimeout = 12;

    /**
     * @var array Alternative channels to use for requests matching specific patterns.
     */
    public $Channels = ['Triggers' => []];

    /**
     * @var string Disabled channels CSV.
     */
    public $Disabled = '';

    /**
     * @var bool Whether to send the results of outbound requests to stdout.
     */
    public $SendToOut = false;

    /**
     * @var string Object-level logger for the results of outbound requests.
     */
    public $ObjLogger = '';

    /**
     * @var string Whether to dump the object-level logger to a file (and where to find it).
     */
    public $ObjLoggerFile = '';

    /**
     * @var string The URL of a proxy to use if required by the instance.
     */
    public $Proxy = '';

    /**
     * @var string The username and password to use if required by the specified proxy URL.
     */
    #[Context(Sensitive: true)]
    public $ProxyAuth = '';

    /**
     * @var string The default user agent to cite (implementations *should* override
     *  this with a user agent of their own, in order to properly inform servers of
     *  the implementation's identity.
     */
    public $UserAgent = 'Request class (https://github.com/Maikuolan/Common)';

    /**
     * @var int The most recent status code generated by the instance.
     */
    public $MostRecentStatusCode = 0;

    /**
     * @var bool Whether to allow using curl for sending requests.
     */
    public $AllowCurl = false;

    /**
     * @var bool Whether to allow using fopen with streams for sending requests.
     */
    public $AllowFOpenWStream = false;

    /**
     * @var bool Whether to allow using fsockopen with streams for sending requests.
     */
    public $AllowFSockOpenWStream = false;

    /**
     * @var array PHP disabled functions (populated by the constructor).
     */
    private $DF = [];

    /**
     * @var array Supported protocols and socket transports (populated by the constructor).
     */
    private $Supported = [1 => [], 2 => ['FTP' => 1, 'FTPS' => 1, 'HTTP' => 1, 'HTTPS' => 1], 3 => ['TCP' => 1, 'UDP' => 1]];

    /**
     * @var float Used by the timer method.
     */
    private $Time = 0.0;

    /**
     * @var int Default stream blocksize (128KB).
     */
    private const STREAM_BLOCKSIZE = 131072;

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        /** Disabled functions check. */
        $this->DF = \array_flip(\explode(',', \ini_get('disable_functions') ?: ''));

        if (
            \extension_loaded('curl') &&
            \function_exists('curl_init') &&
            !isset($this->DF['curl_init']) &&
            \function_exists('curl_setopt') &&
            !isset($this->DF['curl_setopt']) &&
            \function_exists('curl_exec') &&
            !isset($this->DF['curl_exec']) &&
            \function_exists('curl_version') &&
            !isset($this->DF['curl_version'])
        ) {
            $CurlVer = \curl_version();
            if (isset($CurlVer['protocols']) && \is_array($CurlVer['protocols'])) {
                foreach ($CurlVer['protocols'] as $Protocol) {
                    $this->Supported[1][\strtoupper($Protocol)] = 1;
                }
            }
            $this->AllowCurl = true;
        }
        if (!\ini_get('open_basedir') && \ini_get('allow_url_fopen') && \function_exists('feof') && !isset($this->DF['feof']) && \function_exists('fread') && !isset($this->DF['fread'])) {
            $this->AllowFOpenWStream = (
                \function_exists('stream_context_create') &&
                !isset($this->DF['stream_context_create']) &&
                \function_exists('fopen') &&
                !isset($this->DF['fopen'])
            );
            $this->AllowFSockOpenWStream = (
                \function_exists('stream_set_timeout') &&
                !isset($this->DF['stream_set_timeout']) &&
                \function_exists('stream_set_blocking') &&
                !isset($this->DF['stream_set_blocking']) &&
                \function_exists('fsockopen') &&
                !isset($this->DF['fsockopen']) &&
                \function_exists('fwrite') &&
                !isset($this->DF['fwrite'])
            );
        }
    }

    /**
     * Allow calling the instance as a function (proxies to request).
     *
     * @return string
     */
    public function __invoke(...$Params): string
    {
        return $this->request(...$Params);
    }

    /**
     * Object destructor. Used to write the object-level logger to a file when necessary.
     *
     * @return void
     */
    public function __destruct()
    {
        /** Guard. */
        if ($this->ObjLogger === '' || $this->ObjLoggerFile === '') {
            return;
        }

        $WriteMode = \file_exists($this->ObjLoggerFile) ? 'ab' : 'wb';
        $Handle = \fopen($this->ObjLoggerFile, $WriteMode);
        if (!\is_resource($Handle)) {
            return;
        }
        \fwrite($Handle, $this->ObjLogger);
        \fclose($Handle);
    }

    /**
     * The main request method.
     *
     * @param string $URI The resource to request.
     * @param array $Params An optional, associative array of key-value pairs
     *  for any POST fields you may want to send along with your request.
     * @param int $Timeout An optional timeout limit.
     * @param array $Headers An optional array of headers to send with the request.
     * @param int $Depth Recursion depth of the current closure instance.
     * @param string $Method The request method to use (if not GET or POST).
     * @param int $MaxSegments The maximum number of segments to receive (can
     *  sometimes be useful to prevent timeouts for things like DNS lookups).
     * @return string The results of the request, or an empty string upon failure.
     */
    public function request(string $URI, array $Params = [], int $Timeout = -1, array $Headers = [], int $Depth = 0, string $Method = '', int $MaxSegments = -1): string
    {
        /** Option overrides (currently used only for manually overriding CURLOPT_SSL_VERIFYPEER). **/
        $Overrides = [];

        /** Test channel triggers. */
        foreach ($this->Channels['Triggers'] as $TriggerName => $TriggerURI) {
            /** Ensures only the channel data for a channel matching the current URI is loaded for this specific method instance. */
            if (!isset($this->Channels[$TriggerName]) || !\is_array($this->Channels[$TriggerName]) || \substr($URI, 0, \strlen($TriggerURI)) !== $TriggerURI) {
                continue;
            }

            foreach ($this->Channels[$TriggerName] as $Channel => $Options) {
                if (!\is_array($Options) || !isset($Options[$TriggerName])) {
                    continue;
                }
                $Len = \strlen($Options[$TriggerName]);
                if (\substr($URI, 0, $Len) !== $Options[$TriggerName]) {
                    continue;
                }
                unset($Options[$TriggerName]);
                if (empty($Options) || $this->inCsv(\key($Options), $this->Disabled)) {
                    continue;
                }
                $AlternateURI = \current($Options) . \substr($URI, $Len);
                break;
            }
            if ($this->inCsv($TriggerName, $this->Disabled)) {
                if (isset($AlternateURI)) {
                    return $this($AlternateURI, $Params, $Timeout, $Headers, $Depth, $Method, $MaxSegments);
                }
                return '';
            }
            if (isset($this->Channels['Overrides'], $this->Channels['Overrides'][$TriggerName])) {
                $Overrides = $this->Channels['Overrides'][$TriggerName];
            }
            break;
        }

        $Protocol = (($CPos = \strpos($URI, ':')) === false) ? '' : \strtoupper(\substr($URI, 0, $CPos));
        if ($Protocol === '') {
            $this->MostRecentStatusCode = 1;
            return '';
        }

        if ($Protocol === 'FILE') {
            $this->timer();
            $File = \substr($URI, \substr($URI, 4, 3) === '://' ? 7 : 5);
            if ($File === '' || !\is_file($File) || !\is_readable($File)) {
                $this->sendMessage(\sprintf('%s - %s - %s - %s', $Protocol, $URI, 2, $this->timer(false)));
                $this->MostRecentStatusCode = 2;
                return '';
            }
            $Data = \file_get_contents($File);
            if (\is_string($Data)) {
                $this->sendMessage(\sprintf('%s - %s - %s - %s', $Protocol, $URI, 0, $this->timer(false)));
                $this->MostRecentStatusCode = 0;
                return $Data;
            }
            $this->sendMessage(\sprintf('%s - %s - %s - %s', $Protocol, $URI, 2, $this->timer(false)));
            $this->MostRecentStatusCode = 2;
            return '';
        }

        /** Using curl. */
        if ($this->AllowCurl && isset($this->Supported[1][$Protocol])) {
            $this->timer();
            /** Initialise the cURL session. */
            $Request = \curl_init($URI);
            if ($Request === false) {
                $this->MostRecentStatusCode = \curl_errno();
                $this->sendMessage(\sprintf('%s - %s - %s - %s', $Protocol, $URI, $this->MostRecentStatusCode, $this->timer(false)));
                return '';
            }
            \curl_setopt($Request, \CURLOPT_RETURNTRANSFER, true);

            if ($Protocol === 'FTP' || $Protocol === 'FTPS') {
                if (isset($Overrides['CURLOPT_USERPWD'])) {
                    \curl_setopt($Request, \CURLOPT_USERPWD, $Overrides['CURLOPT_USERPWD']);
                } elseif (isset($Params['USERPWD'])) {
                    \curl_setopt($Request, \CURLOPT_USERPWD, $Params['USERPWD']);
                }
                if ($Protocol === 'FTPS') {
                    \curl_setopt($Request, \CURLOPT_SSL_VERIFYPEER, (
                        isset($Overrides['CURLOPT_SSL_VERIFYPEER']) ? !empty($Overrides['CURLOPT_SSL_VERIFYPEER']) : false
                    ));
                    $Cert = $this->getCertPath();
                    if ($Cert !== '') {
                        \curl_setopt($Request, \CURLOPT_CAINFO, $Cert);
                    }
                }

                /** Execute and get the response. */
                $Response = \curl_exec($Request);

                if (($Info = \curl_getinfo($Request)) && \is_array($Info) && isset($Info['http_code'])) {
                    $this->MostRecentStatusCode = $Info['http_code'];
                    $this->sendMessage(\sprintf('%s - %s - %s - %s', $Protocol, $URI, $Info['http_code'], $this->timer(false)));

                    /** Request failed. Try again using an alternative address. */
                    if ($Info['http_code'] >= 400 && isset($AlternateURI) && $Depth < 3) {
                        if (\PHP_VERSION_ID < 80000) {
                            \curl_close($Request);
                        }
                        return $this($AlternateURI, $Params, $Timeout, $Headers, $Depth + 1, $Method, $MaxSegments);
                    }
                } else {
                    $this->MostRecentStatusCode = $Response === false ? 500 : 226;
                    $this->sendMessage(\sprintf('%s - %s - %s - %s', $Protocol, $URI, $this->MostRecentStatusCode, $this->timer(false)));
                }

                /** Close the cURL session (PHP < 8). */
                if (\PHP_VERSION_ID < 80000) {
                    \curl_close($Request);
                }

                /** Return the results of the FTP/S request. */
                return \is_string($Response) ? $Response : '';
            }

            if ($Protocol === 'GOPHER' || $Protocol === 'SFTP' || $Protocol === 'TFTP') {
                $DefaultSuccess = 0;
                if ($Protocol === 'GOPHER') {
                    \curl_setopt($Request, \CURLOPT_PROTOCOLS, \CURLPROTO_GOPHER);
                } elseif ($Protocol === 'SFTP') {
                    \curl_setopt($Request, \CURLOPT_PROTOCOLS, \CURLPROTO_SFTP);
                } else {
                    \curl_setopt($Request, \CURLOPT_PROTOCOLS, \CURLPROTO_TFTP);
                    $DefaultSuccess = 226;
                }

                /** Execute and get the response. */
                $Response = \curl_exec($Request);

                if (\is_string($Response)) {
                    $this->MostRecentStatusCode = $DefaultSuccess;
                    $this->sendMessage(\sprintf('%s - %s - %s - %s', $Protocol, $URI, $this->MostRecentStatusCode, $this->timer(false)));
                } else {
                    $this->MostRecentStatusCode = \curl_errno();
                    $this->sendMessage(\sprintf('%s - %s - %s - %s', $Protocol, $URI, $this->MostRecentStatusCode, $this->timer(false)));

                    /** Request failed. Try again using an alternative address. */
                    if ($this->MostRecentStatusCode > 0 && isset($AlternateURI) && $Depth < 3) {
                        if (\PHP_VERSION_ID < 80000) {
                            \curl_close($Request);
                        }
                        return $this($AlternateURI, $Params, $Timeout, $Headers, $Depth + 1, $Method, $MaxSegments);
                    }
                }

                /** Close the cURL session (PHP < 8). */
                if (\PHP_VERSION_ID < 80000) {
                    \curl_close($Request);
                }

                /** Return the results of the request. */
                return $Response;
            }

            \curl_setopt($Request, \CURLOPT_FRESH_CONNECT, true);
            \curl_setopt($Request, \CURLOPT_HEADER, false);
            if (empty($Params)) {
                \curl_setopt($Request, \CURLOPT_POST, false);
                $Post = false;
            } else {
                \curl_setopt($Request, \CURLOPT_POST, true);
                \curl_setopt($Request, \CURLOPT_POSTFIELDS, $Params);
                $Post = true;
            }
            if ($Protocol === 'HTTPS') {
                \curl_setopt($Request, \CURLOPT_PROTOCOLS, \CURLPROTO_HTTPS);
                \curl_setopt($Request, \CURLOPT_SSL_VERIFYPEER, (
                    isset($Overrides['CURLOPT_SSL_VERIFYPEER']) ? !empty($Overrides['CURLOPT_SSL_VERIFYPEER']) : false
                ));
                $Cert = $this->getCertPath();
                if ($Cert !== '') {
                    \curl_setopt($Request, \CURLOPT_CAINFO, $Cert);
                }
            }
            if ($Method !== '') {
                \curl_setopt($Request, \CURLOPT_CUSTOMREQUEST, $Method);
                $DebugMethod = $Method;
            } else {
                $DebugMethod = $Post ? 'POST' : 'GET';
            }
            if ($this->Proxy !== '') {
                \curl_setopt($Request, \CURLOPT_PROXY, $this->Proxy);
                if ($this->ProxyAuth !== '') {
                    \curl_setopt($Request, \CURLOPT_PROXYUSERPWD, $this->ProxyAuth);
                }
            }
            \curl_setopt($Request, \CURLOPT_FOLLOWLOCATION, true);
            \curl_setopt($Request, \CURLOPT_MAXREDIRS, 1);
            \curl_setopt($Request, \CURLOPT_TIMEOUT, $Timeout > 0 ? $Timeout : $this->DefaultTimeout);
            \curl_setopt($Request, \CURLOPT_USERAGENT, $this->UserAgent);
            \curl_setopt($Request, \CURLOPT_HTTPHEADER, $Headers ?: []);

            /** Execute and get the response. */
            $Response = \curl_exec($Request);

            if (($Info = \curl_getinfo($Request)) && \is_array($Info) && isset($Info['http_code'])) {
                $this->MostRecentStatusCode = $Info['http_code'];
                $this->sendMessage(\sprintf('%s - %s - %s - %s', $DebugMethod, $URI, $Info['http_code'], $this->timer(false)));

                /** Request failed. Try again using an alternative address. */
                if ($Info['http_code'] >= 400 && isset($AlternateURI) && $Depth < 3) {
                    if (\PHP_VERSION_ID < 80000) {
                        \curl_close($Request);
                    }
                    return $this($AlternateURI, $Params, $Timeout, $Headers, $Depth + 1, $Method, $MaxSegments);
                }
            } else {
                $this->MostRecentStatusCode = $Response === false ? 400 : 200;
                $this->sendMessage(\sprintf('%s - %s - %s - %s', $DebugMethod, $URI, $this->MostRecentStatusCode, $this->timer(false)));
            }

            /** Close the cURL session (PHP < 8). */
            if (\PHP_VERSION_ID < 80000) {
                \curl_close($Request);
            }

            /** Return the results of the HTTP/S request. */
            return \is_string($Response) ? $Response : '';
        }

        /** Using fopen with streams. */
        if ($this->AllowFOpenWStream && isset($this->Supported[2][$Protocol])) {
            if ($Protocol === 'FTP' || $Protocol === 'FTPS') {
                $this->timer();
                $Context = ['ftp' => ['timeout' => $Timeout > 0 ? $Timeout : $this->DefaultTimeout, 'ignore_errors' => true]];
                if ($Protocol === 'FTPS') {
                    $Cert = $this->getCertPath();
                    if ($Cert !== '') {
                        $VPeer = isset($Overrides['CURLOPT_SSL_VERIFYPEER']) ? !empty($Overrides['CURLOPT_SSL_VERIFYPEER']) : false;
                        $Context['ssl'] = ['verify_peer' => $VPeer, 'verify_peer_name' => $VPeer, 'allow_self_signed' => false, 'cafile' => $Cert];
                    } else {
                        $Context['ssl'] = ['verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => false, 'cafile' => false];
                    }
                }
                $Context = \stream_context_create($Context);

                if (isset($Overrides['CURLOPT_USERPWD'])) {
                    $HandlePath = $Protocol === 'FTPS' ? 'ftps://' . $Overrides['CURLOPT_USERPWD'] . '@' . \substr($URI, 7) : 'ftp://' . $Overrides['CURLOPT_USERPWD'] . '@' . \substr($URI, 6);
                } elseif (isset($Params['USERPWD'])) {
                    $HandlePath = $Protocol === 'FTPS' ? 'ftps://' . $Params['USERPWD'] . '@' . \substr($URI, 7) : 'ftp://' . $Params['USERPWD'] . '@' . \substr($URI, 6);
                } else {
                    $HandlePath = $URI;
                }
                $Handle = \fopen($HandlePath, 'rb', false, $Context);
                if (!\is_resource($Handle)) {
                    $this->sendMessage(\sprintf('%s - %s - %s - %s', $Protocol, $URI, 500, $this->timer(false)));
                    $this->MostRecentStatusCode = 500;
                    return '';
                }

                /** Content of the request response. */
                $Response = '';
                $Iter = 0;
                while (!\feof($Handle) && ($MaxSegments < 0 || $Iter < $MaxSegments)) {
                    $Iter++;
                    $Segment = \fread($Handle, self::STREAM_BLOCKSIZE);
                    if ($Segment === '' || $Segment === false) {
                        break;
                    }
                    $Response .= $Segment;
                }

                \fclose($Handle);
                $this->sendMessage(\sprintf('%s - %s - %s - %s', $Protocol, $URI, 226, $this->timer(false)));

                /** Assuming 226, because no reliable way to tell otherwise. */
                $this->MostRecentStatusCode = 226;

                /** Return the results of the FTP/S request. */
                return $Response;
            }

            if ($Protocol === 'HTTP' || $Protocol === 'HTTPS') {
                $this->timer();
                if (!empty($Params) && \function_exists('http_build_query') && !isset($this->DF['http_build_query'])) {
                    $Post = true;
                    $PostData = \http_build_query($Params);
                    $Headers['Content-Type'] = 'application/x-www-form-urlencoded';
                } else {
                    $Post = false;
                    $PostData = '';
                }
                if ($Method !== '') {
                    $MethodToUse = $Method;
                } else {
                    $MethodToUse = $Post ? 'POST' : 'GET';
                }
                $Context = ['http' => ['method' => $MethodToUse, 'timeout' => $Timeout > 0 ? $Timeout : $this->DefaultTimeout, 'follow_location' => 1, 'max_redirects' => 1, 'ignore_errors' => true]];
                if (!isset($Headers['Accept-Language'])) {
                    $Headers = ['Accept-Language' => 'en-AU,en-US;q=0.9,en;q=0.8'] + $Headers;
                }
                $Headers['User-Agent'] = $this->UserAgent;
                if ($this->Proxy !== '') {
                    $Context['http']['proxy'] = $this->Proxy;
                    $Context['http']['request_fulluri'] = true;
                    if ($this->ProxyAuth !== '') {
                        $Headers['Proxy-Authorization'] = 'Basic ' . \base64_encode($this->ProxyAuth);
                    }
                }
                $Build = [];
                foreach ($Headers as $HeaderName => $HeaderValue) {
                    $Build[] = $HeaderName . ': ' . $HeaderValue;
                }
                $Context['http']['header'] = \implode("\r\n", $Build);
                unset($HeaderValue, $HeaderName, $Build);
                if ($PostData !== '') {
                    $Context['http']['content'] = $PostData;
                }
                if ($Protocol === 'HTTPS') {
                    $Cert = $this->getCertPath();
                    if ($Cert !== '') {
                        $VPeer = isset($Overrides['CURLOPT_SSL_VERIFYPEER']) ? !empty($Overrides['CURLOPT_SSL_VERIFYPEER']) : false;
                        $Context['ssl'] = ['verify_peer' => $VPeer, 'verify_peer_name' => $VPeer, 'allow_self_signed' => false, 'cafile' => $Cert];
                    } else {
                        $Context['ssl'] = ['verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => false, 'cafile' => false];
                    }
                }
                $Context = \stream_context_create($Context);

                $Handle = \fopen($URI, 'rb', false, $Context);
                if (!\is_resource($Handle)) {
                    $this->sendMessage(\sprintf('%s - %s - %s - %s', $MethodToUse, $URI, 400, $this->timer(false)));
                    $this->MostRecentStatusCode = 400;
                    return '';
                }

                /** Content of the request response. */
                $Response = '';
                $Iter = 0;
                while (!\feof($Handle) && ($MaxSegments < 0 || $Iter < $MaxSegments)) {
                    $Iter++;
                    $Segment = \fread($Handle, self::STREAM_BLOCKSIZE);
                    if ($Segment === '' || $Segment === false) {
                        break;
                    }
                    $Response .= $Segment;
                }

                \fclose($Handle);

                if (\function_exists('http_get_last_response_headers')) {
                    $RHeaders = \http_get_last_response_headers();
                    if (isset($RHeaders[0]) && \substr($RHeaders[0], 0, 4) === 'HTTP' && ($SPos = \strpos($RHeaders[0], ' ')) !== false) {
                        $Code = (int)\substr($RHeaders[0], $SPos + 1, 3);
                    }
                }
                if (isset($Code)) {
                    $this->sendMessage(\sprintf('%s - %s - %s - %s', $MethodToUse, $URI, $Code, $this->timer(false)));
                    $this->MostRecentStatusCode = $Code;

                    /** Request failed. Try again using an alternative address. */
                    if ($Code >= 400 && isset($AlternateURI) && $Depth < 3) {
                        return $this($AlternateURI, $Params, $Timeout, $Headers, $Depth + 1, $Method, $MaxSegments);
                    }
                } else {
                    $this->sendMessage(\sprintf('%s - %s - %s - %s', $MethodToUse, $URI, 200, $this->timer(false)));

                    /** Assuming 200, because no reliable way to tell otherwise without http_get_last_response_headers (and $http_response_header is deprecated as of PHP8.5). */
                    $this->MostRecentStatusCode = 200;
                }

                /** Return the results of the HTTP/S request. */
                return $Response;
            }
        }

        /** Using fsockopen with streams. */
        if ($this->AllowFSockOpenWStream && isset($this->Supported[3][$Protocol])) {
            $this->timer();
            $Port = isset($Params['Port']) ? (int)$Params['Port'] : -1;
            $Handle = \fsockopen($URI, $Port);
            if ($Handle === false) {
                $this->sendMessage(\sprintf('%s - %s - %s - %s', $Method ?: $Protocol, $URI, 2, $this->timer(false)));
                $this->MostRecentStatusCode = 2;
                return '';
            }
            if (isset($Params['Message']) && is_string($Params['Message'])) {
                \fwrite($Handle, $Params['Message']);
            }
            \stream_set_timeout($Handle, $Timeout > 0 ? $Timeout : $this->DefaultTimeout);
            \stream_set_blocking($Handle, true);
            $Response = '';
            $Iter = 0;
            while (!\feof($Handle) && ($MaxSegments < 0 || $Iter < $MaxSegments)) {
                $Iter++;
                $Segment = \fread($Handle, self::STREAM_BLOCKSIZE);
                if ($Segment === '' || $Segment === false) {
                    break;
                }
                $Response .= $Segment;
            }
            \fclose($Handle);
            $this->sendMessage(\sprintf('%s - %s - %s - %s', $Method ?: $Protocol, $URI, 0, $this->timer(false)));
            $this->MostRecentStatusCode = 0;
            return $Response;
        }

        $this->MostRecentStatusCode = 1;
        return '';
    }

    /**
     * Checks for a value within CSV, or within a normal list if not CSV.
     *
     * @param string $Value The value to look for.
     * @param string $CSV The CSV to look in.
     * @return bool True when found; False when not found.
     */
    public function inCsv(string $Value, string $CSV): bool
    {
        if ($Value === '' || $CSV === '') {
            return false;
        }
        $Arr = \strpos($CSV, ',') === false && \strpos($CSV, "\n") !== false ? \explode("\n", $CSV) : \explode(',', $CSV);
        if (\strpos($CSV, '"') !== false) {
            foreach ($Arr as &$Item) {
                if (\substr($Item, 0, 1) === '"' && \substr($Item, -1) === '"') {
                    $Item = \substr($Item, 1, -1);
                }
            }
        }
        return \in_array($Value, $Arr, true);
    }

    /**
     * Sends messages to stdout.
     *
     * @param string $Message The message to send.
     * @return void
     */
    public function sendMessage(string $Message): void
    {
        $this->ObjLogger .= '[' . \date('Y-m-d\Th:i:sO', \time()) . '] ' . $Message . "\n";
        if ($this->SendToOut !== true) {
            return;
        }
        $Handle = \fopen('php://stdout', 'wb');
        \fwrite($Handle, "\r" . $Message . "\n");
        \fclose($Handle);
    }

    /**
     * Gets the certificate path.
     *
     * @return string
     */
    private function getCertPath(): string
    {
        if (!\function_exists('openssl_get_cert_locations') || isset($this->DF['openssl_get_cert_locations'])) {
            return '';
        }
        $Certs = \openssl_get_cert_locations();
        if (!empty($Certs['ini_cafile']) && \is_readable($Certs['ini_cafile'])) {
            return $Certs['ini_cafile'];
        }
        if (!empty($Certs['default_cert_file_env']) && \is_readable($Certs['default_cert_file_env'])) {
            return $Certs['default_cert_file_env'];
        }
        return '';
    }

    /**
     * Starts or stops the timer for message logging.
     *
     * @param bool $OnOff True to start the timer; False to stop it and return the elapsed time in seconds.
     * @return string
     */
    private function timer(bool $OnOff = true): string
    {
        if ($OnOff) {
            $this->Time = \microtime(true);
            return '';
        }
        if ($this->Time > 0.0) {
            $Time = $this->Time;
            $this->Time = 0.0;
            return (\floor((\microtime(true) - $Time) * 100) / 100) . 's';
        }
        return '';
    }
}
