<?php
/**
 * Description to go here.
 *
 * This file: File description here.
 *
 * @package Maikuolan/IPTestScript
 *
 * @todo EVERYTHING! This is still an ALPHA.
 */

/**
 * Prevents execution from outside of IPTestScript.
 */
if(!defined('IPTestScript'))die('[IPTestScript] This should not be accessed directly.');

$IPTestScript['lang']['click_here']='clicca qui';
$IPTestScript['lang']['denied']='Accesso Negato!';
$IPTestScript['lang']['Error_WriteCache']='Non può scrivere nella cache! Si prega di controllare le autorizzazioni di CHMOD!';
$IPTestScript['lang']['field_datetime']='Data/Tempo: ';
$IPTestScript['lang']['field_id']='ID: ';
$IPTestScript['lang']['field_ipaddr']='Indirizzo IP: ';
$IPTestScript['lang']['field_query']='Query: ';
$IPTestScript['lang']['field_referrer']='Referente: ';
$IPTestScript['lang']['field_scriptversion']='Versione dello script: ';
$IPTestScript['lang']['field_sigcount']='Firme Conteggio: ';
$IPTestScript['lang']['field_sigref']='Firme Riferimento: ';
$IPTestScript['lang']['field_ua']='User Agent: ';
$IPTestScript['lang']['generated_by']='Generato da';
$IPTestScript['lang']['preamble']='-- Fine del preambolo. Aggiungere le vostre domande o commenti dopo questa linea. --';
$IPTestScript['lang']['ReasonMessage_BadIP']='Accesso a questa pagina è stato negato perché si è tentato di accedere a questa pagina utilizzando un indirizzo IP non valido.';
$IPTestScript['lang']['ReasonMessage_Bogon']='Accesso a questa pagina è stato negato perché il suo indirizzo IP viene riconosciuto come un indirizzo bogone, e il collegamento da bogoni a questo sito web non è consentito dal proprietario del sito web.';
$IPTestScript['lang']['ReasonMessage_Cloud']='Accesso a questa pagina è stato negato perché il suo indirizzo IP viene riconosciuto come appartenente ad un servizio cloud, e il collegamento a questo sito web da servizi cloud non è consentito dal proprietario del sito web.';
$IPTestScript['lang']['ReasonMessage_Generic']='Accesso a questa pagina è stato negato perché il suo indirizzo IP appartiene a una rete elencati in una lista nera utilizzato da questo sito web.';
$IPTestScript['lang']['ReasonMessage_Spam']='Accesso a questa pagina è stato negato perché il suo indirizzo appartiene a una rete considerati ad alto rischio per lo spam.';
$IPTestScript['lang']['Short_BadIP']='IP non valido!';
$IPTestScript['lang']['Support_Email']='Se credi che questo è in errore, o per cercare assistenza, {ClickHereLink} per inviare una richiesta di assistenza via e-mail per il webmaster di questo sito (si prega di non modificare il preambolo o linea oggetto dell\'e-mail).';
