<?php
/**
 * Description to go here.
 *
 * This file: File description here.
 *
 * @package Maikuolan/IPTestScript
 *
 * @todo EVERYTHING! This is still an ALPHA.
 */

/**
 * Prevents execution from outside of IPTestScript.
 */
if(!defined('IPTestScript'))die('[IPTestScript] This should not be accessed directly.');

$IPTestScript['lang']['click_here']='clic aquí';
$IPTestScript['lang']['denied']='¡Acceso Denegado!';
$IPTestScript['lang']['Error_WriteCache']='No se puede escribir a la caché! Compruebe sus CHMOD permisos!';
$IPTestScript['lang']['field_datetime']='Fecha/Hora: ';
$IPTestScript['lang']['field_id']='ID: ';
$IPTestScript['lang']['field_ipaddr']='Dirección IP: ';
$IPTestScript['lang']['field_query']='Query: ';
$IPTestScript['lang']['field_referrer']='Referente: ';
$IPTestScript['lang']['field_scriptversion']='Guión Versión: ';
$IPTestScript['lang']['field_sigcount']='Firmas Cuentas: ';
$IPTestScript['lang']['field_sigref']='Firmas Referencias: ';
$IPTestScript['lang']['field_ua']='Agente de Usuario: ';
$IPTestScript['lang']['generated_by']='Generado por';
$IPTestScript['lang']['preamble']='-- Fin de la preámbulo. Añadir sus preguntas o comentarios después de esta línea. --';
$IPTestScript['lang']['ReasonMessage_BadIP']='Su acceso a esta página se negó porque porque ha intentado acceder esta página utilizando una dirección IP no válida.';
$IPTestScript['lang']['ReasonMessage_Bogon']='Su acceso a esta página se negó porque su dirección IP se reconoce como una dirección bogon, y la conexión de bogons a este sitio web no está permitido por el propietario del sitio web.';
$IPTestScript['lang']['ReasonMessage_Cloud']='Su acceso a esta página se negó porque su dirección IP se reconoce como perteneciente a un servicio en la nube, y la conexión de servicios en la nube a este sitio web no está permitido por el propietario del sitio web.';
$IPTestScript['lang']['ReasonMessage_Generic']='Su acceso a esta página se negó porque su dirección IP pertenece a una red figuran en una lista negra utilizada por este sitio web.';
$IPTestScript['lang']['ReasonMessage_Spam']='Su acceso a esta página se negó porque su dirección IP pertenece a una red considerados de alto riesgo para el spam.';
$IPTestScript['lang']['Short_BadIP']='IP no válida!';
$IPTestScript['lang']['Support_Email']='Si considera que este es un error, o para buscar ayuda, {ClickHereLink} para enviar un correo electrónico ticket de soporte al webmaster de esta web (por favor, no cambie el preámbulo o la línea de asunto del correo electrónico).';
