<?php
/**
 * Description to go here.
 *
 * This file: File description here.
 *
 * @package Maikuolan/IPTestScript
 *
 * @todo EVERYTHING! This is still an ALPHA.
 */

/**
 * Prevents execution from outside of IPTestScript.
 */
if(!defined('IPTestScript'))die('[IPTestScript] This should not be accessed directly.');

$IPTestScript['lang']['click_here']='klik disini';
$IPTestScript['lang']['denied']='Akses Ditolak!';
$IPTestScript['lang']['Error_WriteCache']='Tidak dapat menulis ke cache! Silakan periksa hak akses file CHMOD Anda!';
$IPTestScript['lang']['field_datetime']='Tanggal/Waktu: ';
$IPTestScript['lang']['field_id']='ID: ';
$IPTestScript['lang']['field_ipaddr']='Alamat IP: ';
$IPTestScript['lang']['field_query']='Kueri: ';
$IPTestScript['lang']['field_referrer']='Halaman Mengacu: ';
$IPTestScript['lang']['field_scriptversion']='Versi Skrip: ';
$IPTestScript['lang']['field_sigcount']='Menghitung Tanda Tangan: ';
$IPTestScript['lang']['field_sigref']='Tanda Tangan Referensi: ';
$IPTestScript['lang']['field_ua']='Agen Pengguna: ';
$IPTestScript['lang']['generated_by']='Dihasilkan oleh';
$IPTestScript['lang']['preamble']='-- Akhir pembukaan. Tambah pertanyaan atau komentar setelah baris ini. --';
$IPTestScript['lang']['ReasonMessage_BadIP']='Akses Anda ke halaman ini ditolak karena Anda mencoba untuk mengakses halaman ini menggunakan alamat IP yang tidak valid.';
$IPTestScript['lang']['ReasonMessage_Bogon']='Akses Anda ke halaman ini ditolak karena alamat IP Anda diakui sebagai alamat bogon, dan menghubungkan dari bogon ke situs ini tidak diizinkan oleh pemilik situs.';
$IPTestScript['lang']['ReasonMessage_Cloud']='Akses Anda ke halaman ini ditolak karena alamat IP Anda diakui sebagai milik dari layanan komputasi awan, dan menghubungkan dari layanan komputasi awan ke situs ini tidak diizinkan oleh pemilik situs.';
$IPTestScript['lang']['ReasonMessage_Generic']='Akses Anda ke halaman ini ditolak karena alamat IP Anda milik dari jaringan terdaftar pada daftar hitam yang digunakan oleh situs ini.';
$IPTestScript['lang']['ReasonMessage_Spam']='Akses Anda ke halaman ini ditolak karena alamat IP Anda milik dari jaringan dianggap berisiko tinggi untuk spam.';
$IPTestScript['lang']['Short_BadIP']='IP tidak valid!';
$IPTestScript['lang']['Support_Email']='Jika Anda yakin ini adalah kesalahan, atau untuk mencari bantuan, {ClickHereLink} untuk mengirim tiket dukungan email ke webmaster dari situs ini (silahkan jangan mengubah pembukaan atau baris subjek email).';
