<?php
/**
 * Description to go here.
 *
 * This file: File description here.
 *
 * @package Maikuolan/IPTestScript
 *
 * @todo EVERYTHING! This is still an ALPHA.
 */

/**
 * Prevents execution from outside of IPTestScript.
 */
if(!defined('IPTestScript'))die('[IPTestScript] This should not be accessed directly.');

$IPTestScript['lang']['click_here']='klik hier';
$IPTestScript['lang']['denied']='Toegang Geweigerd!';
$IPTestScript['lang']['Error_WriteCache']='Kan niet schrijven naar de cache! Controleer uw CHMOD permissies!';
$IPTestScript['lang']['field_datetime']='Datum/Tijd: ';
$IPTestScript['lang']['field_id']='ID: ';
$IPTestScript['lang']['field_ipaddr']='IP-Adres: ';
$IPTestScript['lang']['field_query']='Query: ';
$IPTestScript['lang']['field_referrer']='Verwijzer: ';
$IPTestScript['lang']['field_scriptversion']='Script Versie: ';
$IPTestScript['lang']['field_sigcount']='Handtekeningen Tellen: ';
$IPTestScript['lang']['field_sigref']='Handtekeningen Referentie: ';
$IPTestScript['lang']['field_ua']='User Agent: ';
$IPTestScript['lang']['generated_by']='Gegenereerd door';
$IPTestScript['lang']['preamble']='-- Einde van preambule. Voeg uw vragen of opmerkingen na dit lijn. --';
$IPTestScript['lang']['ReasonMessage_BadIP']='Uw toegang tot dit pagina is geweigerd omdat u geprobeerd om toegang tot dit pagina met behulp van een ongeldig IP-adres.';
$IPTestScript['lang']['ReasonMessage_Bogon']='Uw toegang tot dit pagina is geweigerd omdat uw IP-adres wordt herkend als bogon adres, en het verbinden van bogons naar dit website is niet toegestaan door de eigenaar van dit website.';
$IPTestScript['lang']['ReasonMessage_Cloud']='Uw toegang tot dit pagina is geweigerd omdat uw IP-adres wordt herkend als behorend tot een cloud service, en het verbinden van cloud service naar dit website is niet toegestaan door de eigenaar van dit website.';
$IPTestScript['lang']['ReasonMessage_Generic']='Uw toegang tot dit pagina is geweigerd omdat uw IP-adres behoort tot een netwerk dat is op een zwarte lijst gebruikt door dit website.';
$IPTestScript['lang']['ReasonMessage_Spam']='Uw toegang tot dit pagina is geweigerd omdat uw IP-adres behoort tot een netwerk beschouwd als een hoog risico op spam.';
$IPTestScript['lang']['Short_BadIP']='Ongeldig IP!';
$IPTestScript['lang']['Support_Email']='Als je denkt dat dit een fout, of om hulp te zoeken, {ClickHereLink} om een email support ticket te sturen naar de webmaster van dit site (alsjeblieft niet wijzigen de preambule of de onderwerpregel van de email).';
