<?php
/**
 * This file is a part of the CIDRAM package, and can be downloaded for free
 * from {@link https://github.com/Maikuolan/CIDRAM/ GitHub}.
 *
 * CIDRAM COPYRIGHT 2016 and beyond by Caleb Mazalevskis (Maikuolan).
 *
 * License: GNU/GPLv2
 * @see LICENSE.md
 *
 * This file: Dutch language data (last modified: 2016.02.07).
 *
 * @package Maikuolan/CIDRAM
 */

/** Prevents execution from outside of CIDRAM. */
if (!defined('CIDRAM')) {
    die('[CIDRAM] This should not be accessed directly.');
}

$CIDRAM['lang']['click_here']='klik hier';
$CIDRAM['lang']['denied']='Toegang Geweigerd!';
$CIDRAM['lang']['Error_WriteCache']='Kan niet schrijven naar de cache! Controleer uw CHMOD permissies!';
$CIDRAM['lang']['field_datetime']='Datum/Tijd: ';
$CIDRAM['lang']['field_id']='ID: ';
$CIDRAM['lang']['field_ipaddr']='IP-Adres: ';
$CIDRAM['lang']['field_query']='Query: ';
$CIDRAM['lang']['field_referrer']='Verwijzer: ';
$CIDRAM['lang']['field_scriptversion']='Script Versie: ';
$CIDRAM['lang']['field_sigcount']='Handtekeningen Tellen: ';
$CIDRAM['lang']['field_sigref']='Handtekeningen Referentie: ';
$CIDRAM['lang']['field_ua']='User Agent: ';
$CIDRAM['lang']['generated_by']='Gegenereerd door';
$CIDRAM['lang']['preamble']='-- Einde van preambule. Voeg uw vragen of opmerkingen na dit lijn. --';
$CIDRAM['lang']['ReasonMessage_BadIP']='Uw toegang tot dit pagina is geweigerd omdat u geprobeerd om toegang tot dit pagina met behulp van een ongeldig IP-adres.';
$CIDRAM['lang']['ReasonMessage_Bogon']='Uw toegang tot dit pagina is geweigerd omdat uw IP-adres wordt herkend als bogon adres, en het verbinden van bogons naar dit website is niet toegestaan door de eigenaar van dit website.';
$CIDRAM['lang']['ReasonMessage_Cloud']='Uw toegang tot dit pagina is geweigerd omdat uw IP-adres wordt herkend als behorend tot een cloud service, en het verbinden van cloud service naar dit website is niet toegestaan door de eigenaar van dit website.';
$CIDRAM['lang']['ReasonMessage_Generic']='Uw toegang tot dit pagina is geweigerd omdat uw IP-adres behoort tot een netwerk dat is op een zwarte lijst gebruikt door dit website.';
$CIDRAM['lang']['ReasonMessage_Spam']='Uw toegang tot dit pagina is geweigerd omdat uw IP-adres behoort tot een netwerk beschouwd als een hoog risico op spam.';
$CIDRAM['lang']['Short_BadIP']='Ongeldig IP!';
$CIDRAM['lang']['Support_Email']='Als je denkt dat dit een fout, of om hulp te zoeken, {ClickHereLink} om een email support ticket te sturen naar de webmaster van dit site (alsjeblieft niet wijzigen de preambule of de onderwerpregel van de email).';
