<?php
/**
 * Description to go here.
 *
 * This file: File description here.
 *
 * @package Maikuolan/IPTestScript
 *
 * @todo EVERYTHING! This is still an ALPHA.
 */

/**
 * Prevents execution from outside of IPTestScript.
 */
if(!defined('IPTestScript'))die('[IPTestScript] This should not be accessed directly.');

$IPTestScript['lang']['click_here']='cliquez ici';
$IPTestScript['lang']['denied']='Accès Refusé!';
$IPTestScript['lang']['Error_WriteCache']='Ne peux pas d\'écrire dans le cache! S\'il vous plaît vérifier votre permissions CHMOD!';
$IPTestScript['lang']['field_datetime']='Date/Heure: ';
$IPTestScript['lang']['field_id']='ID: ';
$IPTestScript['lang']['field_ipaddr']='IP Adresse: ';
$IPTestScript['lang']['field_query']='Query: ';
$IPTestScript['lang']['field_referrer']='Referrer: ';
$IPTestScript['lang']['field_scriptversion']='La version du script: ';
$IPTestScript['lang']['field_sigcount']='Signatures Compte: ';
$IPTestScript['lang']['field_sigref']='Signatures Référence: ';
$IPTestScript['lang']['field_ua']='Agent Utilisateur: ';
$IPTestScript['lang']['generated_by']='Généré par';
$IPTestScript['lang']['preamble']='-- Fin du préambule. Ajouter vos questions ou commentaires après cette ligne. --';
$IPTestScript['lang']['ReasonMessage_BadIP']='Votre accès à cette page a été refusée parce que vous avez tenté d\'accéder à cette page en utilisant un invalide IP adresse.';
$IPTestScript['lang']['ReasonMessage_Bogon']='Votre accès à cette page a été refusée parce que votre IP adresse est reconnue comme un bogon adresse, et la connexion de bogons à cette site est pas autorisée par le propriétaire du site.';
$IPTestScript['lang']['ReasonMessage_Cloud']='Votre accès à cette page a été refusée parce que votre IP adresse est reconnue comme appartenant à un service de cloud computing, et la connexion de services de cloud computing à cette site est pas autorisée par le propriétaire du site.';
$IPTestScript['lang']['ReasonMessage_Generic']='Votre accès à cette page a été refusée parce que votre IP adresse appartient à un réseau figurant sur une liste noire utilisée par ce site.';
$IPTestScript['lang']['ReasonMessage_Spam']='Votre accès à cette page a été refusée parce que votre IP adresse appartient à un réseau considéré comme à haut risque pour le spam.';
$IPTestScript['lang']['Short_BadIP']='Invalide IP!';
$IPTestScript['lang']['Support_Email']='Si vous croyez que cela est dans l\'erreur, ou pour demander de l\'aide, {ClickHereLink} pour envoyer un e-mail ticket de support au webmaster de ce site (s\'il vous plaît, ne pas modifier le préambule ou la ligne d\'objet de l\'e-mail).';
