<?php
/**
 * This file is a part of the CIDRAM package.
 * Homepage: https://cidram.github.io/
 *
 * CIDRAM COPYRIGHT 2016 and beyond by Caleb Mazalevskis (Maikuolan).
 *
 * License: GNU/GPLv2
 * @see LICENSE.txt
 *
 * This file: English language data (last modified: 2017.12.21).
 */

/** Prevents execution from outside of CIDRAM. */
if (!defined('CIDRAM')) {
    die('[CIDRAM] This should not be accessed directly.');
}

$CIDRAM['lang']['click_here'] = 'click here';
$CIDRAM['lang']['denied'] = 'Access Denied!';
$CIDRAM['lang']['Error_WriteCache'] = 'Unable to write to the cache! Please check your CHMOD file permissions!';
$CIDRAM['lang']['fake_ua'] = 'Fake {ua}';
$CIDRAM['lang']['field_datetime'] = 'Date/Time: ';
$CIDRAM['lang']['field_hostname'] = 'Hostname: ';
$CIDRAM['lang']['field_id'] = 'ID: ';
$CIDRAM['lang']['field_ipaddr'] = 'IP Address: ';
$CIDRAM['lang']['field_ipaddr_resolved'] = 'IP Address (Resolved): ';
$CIDRAM['lang']['field_query'] = 'Query: ';
$CIDRAM['lang']['field_reCAPTCHA_state'] = 'reCAPTCHA State: ';
$CIDRAM['lang']['field_referrer'] = 'Referrer: ';
$CIDRAM['lang']['field_rURI'] = 'Reconstructed URI: ';
$CIDRAM['lang']['field_scriptversion'] = 'Script Version: ';
$CIDRAM['lang']['field_sigcount'] = 'Signatures Count: ';
$CIDRAM['lang']['field_sigref'] = 'Signatures Reference: ';
$CIDRAM['lang']['field_ua'] = 'User Agent: ';
$CIDRAM['lang']['field_whyreason'] = 'Why Blocked: ';
$CIDRAM['lang']['generated_by'] = 'Generated by';
$CIDRAM['lang']['preamble'] = '-- End of preamble. Add your questions or comments after this line. --';
$CIDRAM['lang']['ReasonMessage_BadIP'] = 'Your access to this page was denied because you attempted to access this page using an invalid IP address.';
$CIDRAM['lang']['ReasonMessage_Banned'] = 'Your access to this page was denied due to previous bad behaviour from your IP address.';
$CIDRAM['lang']['ReasonMessage_Bogon'] = 'Your access to this page was denied because your IP address is recognised as a bogon address, and connecting from bogons to this website isn\'t permitted by the website owner.';
$CIDRAM['lang']['ReasonMessage_Cloud'] = 'Your access to this page was denied because your IP address is recognised as belonging to a cloud service, and connecting to this website from cloud services isn\'t permitted by the website owner.';
$CIDRAM['lang']['ReasonMessage_Generic'] = 'Your access to this page was denied because your IP address belongs to a network listed on a blacklist used by this website.';
$CIDRAM['lang']['ReasonMessage_Proxy'] = 'Your access to this page was denied because your IP address is recognised as belonging to a proxy service, and connecting to this website from proxy services isn\'t permitted by the website owner.';
$CIDRAM['lang']['ReasonMessage_Spam'] = 'Your access to this page was denied because your IP address belongs to a network considered high-risk for spam.';
$CIDRAM['lang']['recaptcha_cookie_warning'] = 'Note: CIDRAM uses a cookie to remember when users complete the CAPTCHA. By completing the CAPTCHA, you give your consent for a cookie to be created and stored by your browser.';
$CIDRAM['lang']['recaptcha_disabled'] = 'Disabled.';
$CIDRAM['lang']['recaptcha_enabled'] = 'Enabled.';
$CIDRAM['lang']['recaptcha_failed'] = 'Failed!';
$CIDRAM['lang']['recaptcha_message'] = 'In order to regain access to this page, please complete the CAPTCHA supplied below and press the submit button.';
$CIDRAM['lang']['recaptcha_message_invisible'] = 'For most users, the page should refresh and restore normal access. In some cases, you may be required to complete a CAPTCHA challenge.';
$CIDRAM['lang']['recaptcha_passed'] = 'Passed!';
$CIDRAM['lang']['recaptcha_submit'] = 'Submit';
$CIDRAM['lang']['Short_BadIP'] = 'Invalid IP';
$CIDRAM['lang']['Short_Banned'] = 'Banned';
$CIDRAM['lang']['Short_Bogon'] = 'Bogon IP';
$CIDRAM['lang']['Short_Cloud'] = 'Cloud service';
$CIDRAM['lang']['Short_Generic'] = 'Generic';
$CIDRAM['lang']['Short_Proxy'] = 'Proxy';
$CIDRAM['lang']['Short_Spam'] = 'Spam risk';
$CIDRAM['lang']['Support_Email'] = 'If you believe this is in error, or to seek assistance, {ClickHereLink} to send an email support ticket to the webmaster of this website (please don\'t change the preamble or subject line of the email).';
$CIDRAM['lang']['Support_Email_2'] = 'If you believe this is in error, send an email to {EmailAddr} to seek assistance.';
