<?php
/**
 * Description to go here.
 *
 * This file: File description here.
 *
 * @package Maikuolan/IPTestScript
 *
 * @todo EVERYTHING! This is still an ALPHA.
 */

/**
 * Prevents execution from outside of IPTestScript.
 */
if(!defined('IPTestScript'))die('[IPTestScript] This should not be accessed directly.');

$IPTestScript['lang']['click_here']='clique aqui';
$IPTestScript['lang']['denied']='Acesso Negado!';
$IPTestScript['lang']['Error_WriteCache']='Não é possível gravar para o cache! Por favor verifique suas permissões CHMOD!';
$IPTestScript['lang']['field_datetime']='Data/Hora: ';
$IPTestScript['lang']['field_id']='ID: ';
$IPTestScript['lang']['field_ipaddr']='Endereço IP: ';
$IPTestScript['lang']['field_query']='Query: ';
$IPTestScript['lang']['field_referrer']='Referente: ';
$IPTestScript['lang']['field_scriptversion']='Versão do Roteiro: ';
$IPTestScript['lang']['field_sigcount']='Contagem da Assinaturas: ';
$IPTestScript['lang']['field_sigref']='Assinaturas Referência: ';
$IPTestScript['lang']['field_ua']='Agente de Usuário: ';
$IPTestScript['lang']['generated_by']='Gerado por';
$IPTestScript['lang']['preamble']='-- Fim de preâmbulo. Adicionar suas perguntas ou comentários após esta linha. --';
$IPTestScript['lang']['ReasonMessage_BadIP']='O seu acesso a esta página foi negado porque você tentou acessar a página usando um endereço IP inválido.';
$IPTestScript['lang']['ReasonMessage_Bogon']='O seu acesso a esta página foi negado porque seu endereço IP é reconhecida como um endereço bogon, e conectando a partir de bogons a este site não é permitido pelo dono do site.';
$IPTestScript['lang']['ReasonMessage_Cloud']='O seu acesso a esta página foi negado porque seu endereço IP é reconhecida como pertencente a um serviço de nuvem, e conectando a partir de serviços em nuvem a este site não é permitido pelo dono do site.';
$IPTestScript['lang']['ReasonMessage_Generic']='O seu acesso a esta página foi negado porque seu endereço IP pertence a uma rede listados em uma lista negra usada por este site.';
$IPTestScript['lang']['ReasonMessage_Spam']='O seu acesso a esta página foi negado porque seu endereço IP pertence a uma rede considerado de alto risco de spam.';
$IPTestScript['lang']['Short_BadIP']='IP inválido!';
$IPTestScript['lang']['Support_Email']='Se você acredita que isso é um erro, ou a procurar assistência, {ClickHereLink} para enviar um e-mail ticket de suporte para o webmaster deste site (por favor, não alterar o preâmbulo ou linha de assunto do e-mail).';
