<?php
/**
 * Description to go here.
 *
 * This file: File description here.
 *
 * @package Maikuolan/IPTestScript
 *
 * @todo EVERYTHING! This is still an ALPHA.
 */

/**
 * Prevents execution from outside of IPTestScript.
 */
if(!defined('IPTestScript'))die('[IPTestScript] This should not be accessed directly.');

$IPTestScript['lang']['click_here']='點擊這裡';
$IPTestScript['lang']['denied']='拒絕訪問！';
$IPTestScript['lang']['Error_WriteCache']='無法寫入緩存！請檢查您的CHMOD文件的權限！';
$IPTestScript['lang']['field_datetime']='日期/時間: ';
$IPTestScript['lang']['field_id']='ID: ';
$IPTestScript['lang']['field_ipaddr']='IP地址: ';
$IPTestScript['lang']['field_query']='網頁查詢: ';
$IPTestScript['lang']['field_referrer']='引薦: ';
$IPTestScript['lang']['field_scriptversion']='腳本版本: ';
$IPTestScript['lang']['field_sigcount']='簽名計數: ';
$IPTestScript['lang']['field_sigref']='簽名參考: ';
$IPTestScript['lang']['field_ua']='用戶代理: ';
$IPTestScript['lang']['generated_by']='所產生通過';
$IPTestScript['lang']['preamble']='-- 結束序言。添加您的問題或意見該行之後。 --';
$IPTestScript['lang']['ReasonMessage_BadIP']='您的訪問這個頁面被拒絕因為您試圖訪問該頁面使用一個無效的IP地址。';
$IPTestScript['lang']['ReasonMessage_Bogon']='您的訪問這個頁面被拒絕因為您的IP地址被識別作為火星IP地址，和來自這些IP連接不是由網站所有者允許。';
$IPTestScript['lang']['ReasonMessage_Cloud']='您的訪問這個頁面被拒絕因為您的IP地址被識別為屬於雲服務，和來自這些IP連接不是由網站所有者允許。';
$IPTestScript['lang']['ReasonMessage_Generic']='您的訪問這個頁面被拒絕因為您的IP地址屬於一個網絡在黑名單中所列使用本網站。';
$IPTestScript['lang']['ReasonMessage_Spam']='您的訪問這個頁面被拒絕因為您的IP地址屬於一個網絡被認為是高風險的垃圾郵件。';
$IPTestScript['lang']['Short_BadIP']='無效的IP！';
$IPTestScript['lang']['Support_Email']='如果您認為這是錯誤的，或尋求援助，{ClickHereLink}發送電子郵件支持票本網站的網站管理員（請不要改變序言或主題行）。';
