<?php
/**
 * Description to go here.
 *
 * This file: File description here.
 *
 * @package Maikuolan/IPTestScript
 *
 * @todo EVERYTHING! This is still an ALPHA.
 */

/**
 * Prevents execution from outside of IPTestScript.
 */
if(!defined('IPTestScript'))die('[IPTestScript] This should not be accessed directly.');

$IPTestScript['lang']['click_here']='点击这里';
$IPTestScript['lang']['denied']='拒绝访问！';
$IPTestScript['lang']['Error_WriteCache']='无法写入缓存！请检查您的CHMOD文件的权限！';
$IPTestScript['lang']['field_datetime']='日期/时间: ';
$IPTestScript['lang']['field_id']='ID: ';
$IPTestScript['lang']['field_ipaddr']='IP地址: ';
$IPTestScript['lang']['field_query']='网页查询: ';
$IPTestScript['lang']['field_referrer']='引荐: ';
$IPTestScript['lang']['field_scriptversion']='脚本版本: ';
$IPTestScript['lang']['field_sigcount']='签名计数: ';
$IPTestScript['lang']['field_sigref']='签名参考: ';
$IPTestScript['lang']['field_ua']='用户代理: ';
$IPTestScript['lang']['generated_by']='所产生通过';
$IPTestScript['lang']['preamble']='-- 结束序言。添加您的问题或意见该行之后。 --';
$IPTestScript['lang']['ReasonMessage_BadIP']='您的访问这个页面被拒绝因为您试图访问该页面使用一个无效的IP地址。';
$IPTestScript['lang']['ReasonMessage_Bogon']='您的访问这个页面被拒绝因为您的IP地址被识别作为火星IP地址，和来自这些IP连接不是由网站所有者允许。';
$IPTestScript['lang']['ReasonMessage_Cloud']='您的访问这个页面被拒绝因为您的IP地址被识别为属于云服务，和来自这些IP连接不是由网站所有者允许。';
$IPTestScript['lang']['ReasonMessage_Generic']='您的访问这个页面被拒绝因为您的IP地址属于一个网络在黑名单中所列使用本网站。';
$IPTestScript['lang']['ReasonMessage_Spam']='您的访问这个页面被拒绝因为您的IP地址属于一个网络被认为是高风险的垃圾邮件。';
$IPTestScript['lang']['Short_BadIP']='无效的IP！';
$IPTestScript['lang']['Support_Email']='如果您认为这是错误的，或寻求援助，{ClickHereLink}发送电子邮件支持票本网站的网站管理员（请不要改变序言或主题行）。';
